In [16]:
from pathlib import Path
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme(style="whitegrid")

In [20]:
data_path = Path("/Users/ssokolov/Documents/coding/FlightDelayPrediction/FlightData/flight_delays_2025_07.csv")
df = pd.read_csv(data_path)

#Information about the dataset July
display(df.head())
print("Rows and columns: ", df.shape)
print(df.columns.tolist())
df.info()
df.describe()

,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,Reporting_Airline,Flight_Number_Reporting_Airline,Origin,OriginCityName,...,Diverted,CRSElapsedTime,ActualElapsedTime,AirTime,Distance,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2025,3,7,23,3,2025-07-23,AA,969,MIA,"Miami, FL",...,0.0,130.0,128.0,91.0,650.0,NaN,NaN,NaN,NaN,NaN
1,2025,3,7,24,4,2025-07-24,AA,969,MIA,"Miami, FL",...,0.0,130.0,119.0,94.0,650.0,0.0,0.0,0.0,0.0,74.0
2,2025,3,7,25,5,2025-07-25,AA,969,MIA,"Miami, FL",...,0.0,130.0,116.0,89.0,650.0,NaN,NaN,NaN,NaN,NaN
3,2025,3,7,26,6,2025-07-26,AA,969,MIA,"Miami, FL",...,0.0,130.0,145.0,87.0,650.0,NaN,NaN,NaN,NaN,NaN
4,2025,3,7,27,7,2025-07-27,AA,969,MIA,"Miami, FL",...,0.0,130.0,113.0,94.0,650.0,NaN,NaN,NaN,NaN,NaN

Rows and columns:  (631428, 40)
['Year', 'Quarter', 'Month', 'DayofMonth', 'DayOfWeek', 'FlightDate', 'Reporting_Airline', 'Flight_Number_Reporting_Airline', 'Origin', 'OriginCityName', 'OriginState', 'Dest', 'DestCityName', 'DestState', 'CRSDepTime', 'DepTime', 'DepDelay', 'DepDelayMinutes', 'DepDel15', 'TaxiOut', 'WheelsOff', 'WheelsOn', 'TaxiIn', 'CRSArrTime', 'ArrTime', 'ArrDelay', 'ArrDelayMinutes', 'ArrDel15', 'Cancelled', 'CancellationCode', 'Diverted', 'CRSElapsedTime', 'ActualElapsedTime', 'AirTime', 'Distance', 'CarrierDelay', 'WeatherDelay', 'NASDelay', 'SecurityDelay', 'LateAircraftDelay']
<class 'pandas.DataFrame'>
RangeIndex: 631428 entries, 0 to 631427
Data columns (total 40 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   Year                             631428 non-null  int64
 1   Quarter                          631428 non-null  int64
 2   Month                            631428 non-null  int64
 3   DayofMonth                       631428 non-null  int64
 4   DayOfWeek                        631428 non-null  int64
 5   FlightDate                       631428 non-null  str
 6   Reporting_Airline                631428 non-null  str
 7   Flight_Number_Reporting_Airline  631428 non-null  int64
 8   Origin                           631428 non-null  str
 9   OriginCityName                   631428 non-null  str
 10  OriginState                      631428 non-null  str
 11  Dest                             631428 non-null  str
 12  DestCityName                     631428 non-null  str
 13  DestState                        631428 non-null  str
 14  CRSDepTime                       631428 non-null  int64
 15  DepTime                          616941 non-null  float64
 16  DepDelay                         616879 non-null  float64
 17  DepDelayMinutes                  616879 non-null  float64
 18  DepDel15                         616879 non-null  float64
 19  TaxiOut                          616027 non-null  float64
 20  WheelsOff                        616027 non-null  float64
 21  WheelsOn                         615731 non-null  float64
 22  TaxiIn                           615731 non-null  float64
 23  CRSArrTime                       631428 non-null  int64
 24  ArrTime                          615731 non-null  float64
 25  ArrDelay                         612811 non-null  float64
 26  ArrDelayMinutes                  612811 non-null  float64
 27  ArrDel15                         612811 non-null  float64
 28  Cancelled                        631428 non-null  float64
 29  CancellationCode                 15473 non-null   str
 30  Diverted                         631428 non-null  float64
 31  CRSElapsedTime                   631428 non-null  float64
 32  ActualElapsedTime                612811 non-null  float64
 33  AirTime                          612811 non-null  float64
 34  Distance                         631428 non-null  float64
 35  CarrierDelay                     177012 non-null  float64
 36  WeatherDelay                     177012 non-null  float64
 37  NASDelay                         177012 non-null  float64
 38  SecurityDelay                    177012 non-null  float64
 39  LateAircraftDelay                177012 non-null  float64
dtypes: float64(23), int64(8), str(9)
memory usage: 192.7 MB

,Year,Quarter,Month,DayofMonth,DayOfWeek,Flight_Number_Reporting_Airline,CRSDepTime,DepTime,DepDelay,DepDelayMinutes,...,Diverted,CRSElapsedTime,ActualElapsedTime,AirTime,Distance,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
count,631428.0,631428.0,631428.0,631428.000000,631428.000000,631428.000000,631428.000000,616941.000000,616879.000000,616879.000000,...,631428.000000,631428.000000,612811.000000,612811.000000,631428.000000,177012.000000,177012.000000,177012.000000,177012.000000,177012.000000
mean,2025.0,3.0,7.0,16.152681,3.896839,2518.548965,1332.384418,1332.758902,21.512554,24.369165,...,0.004979,148.913105,144.908102,117.221213,856.773176,25.297155,5.974335,16.864608,0.086265,33.221928
std,0.0,0.0,0.0,8.886865,1.952055,1623.405024,503.046152,532.424783,70.177479,69.078137,...,0.070388,72.845332,73.733791,71.166497,610.417342,78.829476,39.896855,41.466763,2.892283,66.950938
min,2025.0,3.0,7.0,1.000000,1.000000,1.000000,4.000000,1.000000,-60.000000,0.000000,...,0.000000,31.000000,16.000000,7.000000,31.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2025.0,3.0,7.0,9.000000,2.000000,1219.000000,902.000000,858.000000,-5.000000,0.000000,...,0.000000,95.000000,91.000000,64.000000,406.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2025.0,3.0,7.0,16.000000,4.000000,2266.000000,1325.000000,1323.000000,-1.000000,0.000000,...,0.000000,132.000000,128.000000,100.000000,696.000000,3.000000,0.000000,0.000000,0.000000,7.000000
75%,2025.0,3.0,7.0,24.000000,6.000000,3631.000000,1745.000000,1800.000000,20.000000,20.000000,...,0.000000,180.000000,177.000000,147.000000,1090.000000,21.000000,0.000000,18.000000,0.000000,40.000000
max,2025.0,3.0,7.0,31.000000,7.000000,9911.000000,2400.000000,2400.000000,2560.000000,2560.000000,...,1.000000,665.000000,720.000000,644.000000,5095.000000,2557.000000,1817.000000,1387.000000,534.000000,2188.000000

In [22]:
#Inspecting the Dataset
missing_summary = pd.DataFrame({
    "missing_count": df.isna().sum(),
    "missing_percent": df.isna().mean() * 100,
}).sort_values("missing_percent", ascending=False)

display(missing_summary)
print("Exact duplicate rows:", df.duplicated().sum())

                                 missing_count  missing_percent
CancellationCode                        615955        97.549523
LateAircraftDelay                       454416        71.966400
SecurityDelay                           454416        71.966400
NASDelay                                454416        71.966400
WeatherDelay                            454416        71.966400
CarrierDelay                            454416        71.966400
AirTime                                  18617         2.948396
ActualElapsedTime                        18617         2.948396
ArrDel15                                 18617         2.948396
ArrDelayMinutes                          18617         2.948396
ArrDelay                                 18617         2.948396
ArrTime                                  15697         2.485952
TaxiIn                                   15697         2.485952
WheelsOn                                 15697         2.485952
TaxiOut                                  15401         2.439075
WheelsOff                                15401         2.439075
DepDelay                                 14549         2.304142
DepDel15                                 14549         2.304142
DepDelayMinutes                          14549         2.304142
DepTime                                  14487         2.294323
Diverted                                     0         0.000000
Month                                        0         0.000000
DayofMonth                                   0         0.000000
DayOfWeek                                    0         0.000000
FlightDate                                   0         0.000000
Distance                                     0         0.000000
Reporting_Airline                            0         0.000000
Flight_Number_Reporting_Airline              0         0.000000
CRSElapsedTime                               0         0.000000
Cancelled                                    0         0.000000
Origin                                       0         0.000000
OriginCityName                               0         0.000000
OriginState                                  0         0.000000
Dest                                         0         0.000000
DestCityName                                 0         0.000000
CRSArrTime                                   0         0.000000
DestState                                    0         0.000000
CRSDepTime                                   0         0.000000
Quarter                                      0         0.000000
Year                                         0         0.000000

Exact duplicate rows: 0

In [24]:
display(df["Cancelled"].value_counts(dropna=False))
display(df["Diverted"].value_counts(dropna=False))
display(df["ArrDelay"].describe())

Cancelled
0.0    615955
1.0     15473
Name: count, dtype: int64

Diverted
0.0    628284
1.0      3144
Name: count, dtype: int64

count    612811.000000
mean         17.346069
std          72.063374
min         -83.000000
25%         -13.000000
50%          -3.000000
75%          20.000000
max        2557.000000
Name: ArrDelay, dtype: float64

In [27]:
#Dates preparation 
df["FlightDate"] = pd.to_datetime(
    df["FlightDate"],
    errors='coerce'
)
df["Month"] = df["FlightDate"].dt.month
df["weekday"] = df["FlightDate"].dt.dayofweek

completed = df.loc[
    df["Cancelled"].eq(0)
    & df["Diverted"].eq(0)
    & df["ArrDelay"].notna()
].copy()
completed["is_delayed"] = completed["ArrDelay"].ge(15)
completed["positive_delay"] = completed["ArrDelay"].clip(lower=0)